language: python
python:
  - "3.6"
cache:
  - pip: true
  - directories:
    - $HOME/.local/share/io.parity.ethereum/
    - $TRAVIS_BUILD_DIR/paritybin
services:
  - postgresql
  - rabbitmq
before_install:
  - createdb ether_sql_tests
  - sudo -u postgres psql -U travis -d postgres -c "alter user travis with password 'develop';"
  - sudo rabbitmqctl add_user myuser mypassword
  - sudo rabbitmqctl add_vhost myvhost
  - sudo rabbitmqctl set_user_tags myuser mytag
  - sudo rabbitmqctl set_permissions -p myvhost myuser ".*" ".*" ".*"
install:
  - travis_retry pip install -e . -r requirements.txt
  - python tests/parity_local/install_parity.py v1.11.7
script:
- # python -m pytest -vv tests/infura
- python -m pytest -svv tests/parity_local
